#!/usr/bin/env python3
"""Regenerates src/cp932_table.h, the Shift-JIS to Unicode table.

The table is data, not a decision: it is the mapping Python's own cp932 codec
carries, written out as a C array so the engine needs no iconv and no library.
Run from the repository root:

    python3 tools/gen_cp932.py > src/cp932_table.h
"""
import sys

LEAD_RANGES = [(0x81, 0x9f), (0xe0, 0xfc)]
TRAIL_FIRST, TRAIL_LAST = 0x40, 0xfc


def main():
    leads = [b for lo, hi in LEAD_RANGES for b in range(lo, hi + 1)]
    out = sys.stdout
    out.write("/* Generated by tools/gen_cp932.py from Python's cp932 codec. Do not edit. */\n")
    out.write("#ifndef CP932_TABLE_H\n#define CP932_TABLE_H\n\n")
    out.write("#define CP932_TRAIL_FIRST 0x%02x\n" % TRAIL_FIRST)
    out.write("#define CP932_TRAIL_LAST  0x%02x\n" % TRAIL_LAST)
    out.write("#define CP932_TRAIL_SPAN  %d\n" % (TRAIL_LAST - TRAIL_FIRST + 1))
    out.write("#define CP932_ROWS        %d\n\n" % len(leads))
    out.write("static const unsigned short cp932_table[CP932_ROWS][CP932_TRAIL_SPAN] = {\n")
    for lead in leads:
        row = []
        for trail in range(TRAIL_FIRST, TRAIL_LAST + 1):
            try:
                code = ord(bytes([lead, trail]).decode("cp932"))
                if code > 0xffff:
                    code = 0xfffd
            except Exception:
                code = 0
            row.append(code)
        out.write("    { /* lead 0x%02x */\n" % lead)
        for i in range(0, len(row), 12):
            out.write("        " + " ".join("0x%04x," % c for c in row[i:i + 12]) + "\n")
        out.write("    },\n")
    out.write("};\n\n#endif\n")


if __name__ == "__main__":
    main()
